---
title: "About"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Background
 I'm an aspiring statistician/data scientist looking to distill large, complex, and structured/unstructured data into meaningful actions that have direct and measurable impact on a company's processes and decisions. My passion is translating data into actionable intelligence, solving a myriad of business problems, and enabling business strategies.
 
 <hr>

## Skills

Experimental Design (ANOVA), Regression Analysis, Machine Learning, Data Mining, Statistical Inference, Multivariate Analysis, Statistical and Quantitative Analysis, Computational Statistics, Random Processes, and Mathematical Modeling.

<hr>

## Statistical Programming Tools:

<h4> Proficient: </h4>
*R, SQL, Tableau, Excel, PowerPoint*

#### Familiar With:
*Python, Java, C++, HTML, MS Office*